[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@uniswap/=node_modules/@uniswap/',
    'canonical-weth/=node_modules/canonical-weth/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
]
test = 'test/foundry'
cache_path = 'forge-cache'
gas_reports = ["*"]
fs_permissions = [
    { access = "read-write", path = "./test/foundry/script/" },
    { access = "read", path = "./deployments/" },
]
memory_limit = 9223372036854775807
solc_version = "0.8.17"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
